Repository appuio/cloud-portal, pull requests merged in 2022-04, with the labels that each got.

#138 Show join organization dialog only when person is not in any organization
  .gitignore
  README.md
  angular.json
  cypress/fixtures/organization-list-empty.json
  cypress/fixtures/organization-list.json
  cypress/fixtures/organization-members-nxt-without-current-username.json
  cypress/fixtures/organization-members-nxt.json
  cypress/fixtures/organization-members-vshn.json
  cypress/fixtures/organization-update.json
  cypress/fixtures/teams-empty.json
  cypress/fixtures/teams.json
  cypress/fixtures/well-known.json
  cypress/fixtures/zone-list-empty.json
  cypress/fixtures/zone-list.json
  cypress/integration/first-time-login.spec.ts
  cypress/integration/organization-members.spec.ts
  cypress/integration/organizations.spec.ts
  cypress/integration/status.spec.ts
  cypress/integration/teams.spec.ts
  cypress/integration/zones.spec.ts
  cypress/support/commands.ts
  package-lock.json
  package.json
  src/app/app-config.service.ts
  src/app/app.component.ts
  src/app/core/identity.service.ts
  src/app/core/kubernetes-client.service.ts
  src/app/first-time-login-dialog/first-time-login-dialog.component.html
  src/app/first-time-login-dialog/first-time-login-dialog.component.ts
  src/app/organizations/join-organization-dialog/join-organization-dialog.component.ts
  src/app/organizations/organization-members-edit/organization-members-edit.component.ts
  src/app/organizations/organizations.component.ts
  src/app/teams/join-team-dialog/join-team-dialog.component.ts
  src/app/types/organization-members.ts
  src/config.json
  src/environments/environment.e2e-development.ts
  src/environments/environment.prod.ts
  src/environments/environment.production.ts
  src/environments/environment.ts
  src/environments/environment.type.ts
  src/style/theme.css
Labels: bug

#148 Antora Documentation
  docs/antora.yml
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/index.adoc
Labels: documentation

#150 Organizations management page
  .github/workflows/triggerci.yml
  Makefile
  docs/modules/ROOT/assets/images/appuio-cloud.svg
  docs/modules/ROOT/assets/images/how-to/organizations/empty.png
  docs/modules/ROOT/assets/images/how-to/organizations/list.png
  docs/modules/ROOT/assets/images/how-to/organizations/members.png
  docs/modules/ROOT/assets/images/how-to/organizations/new.png
  docs/modules/ROOT/assets/images/how-to/organizations/username.png
  docs/modules/ROOT/assets/images/how-to/organizations/welcome.png
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/.vale.ini
  docs/modules/ROOT/pages/how-to/find-username.adoc
  docs/modules/ROOT/pages/how-to/organizations.adoc
  docs/modules/ROOT/pages/index.adoc
Labels: documentation

#151 Teams management
  docs/modules/ROOT/assets/images/how-to/teams/join.png
  docs/modules/ROOT/assets/images/how-to/teams/list.png
  docs/modules/ROOT/assets/images/how-to/teams/members.png
  docs/modules/ROOT/assets/images/how-to/teams/new.png
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/how-to/teams.adoc
Labels: documentation

#147 Enable users to set their default organization
  cypress/fixtures/organization-list-empty.json
  cypress/fixtures/organization-list.json
  cypress/fixtures/organization-members-nxt-without-current-username.json
  cypress/fixtures/organization-members-nxt.json
  cypress/fixtures/organization-members-vshn.json
  cypress/fixtures/organization-members.json
  cypress/fixtures/organization-members.ts
  cypress/fixtures/organization-update.json
  cypress/fixtures/organization.ts
  cypress/fixtures/team.ts
  cypress/fixtures/team1-update.json
  cypress/fixtures/team1.json
  cypress/fixtures/teams-empty.json
  cypress/fixtures/teams.json
  cypress/fixtures/user.ts
  cypress/fixtures/zone-list-empty.json
  cypress/fixtures/zone-list.json
  cypress/fixtures/zone.ts
  cypress/integration/first-time-login.spec.ts
  cypress/integration/organization-members.spec.ts
  cypress/integration/organizations.spec.ts
  cypress/integration/status.spec.ts
  cypress/integration/teams.spec.ts
  cypress/integration/user.spec.ts
  cypress/integration/zones.spec.ts
  cypress/tsconfig.json
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/core/kubernetes-client.service.ts
  src/app/organization-selection/organization-selection.component.html
  src/app/organization-selection/organization-selection.component.scss
  src/app/organization-selection/organization-selection.component.ts
  src/app/organizations/organization-form/organization-form.component.ts
  src/app/organizations/store/organization.actions.ts
  src/app/organizations/store/organization.effects.ts
  src/app/store/app.actions.ts
  src/app/store/app.effects.ts
  src/app/store/app.reducer.ts
  src/app/store/app.selectors.ts
  src/app/teams/store/team.actions.ts
  src/app/teams/store/team.effects.ts
  src/app/teams/teams.component.ts
  src/app/teams/teams.module.ts
  src/app/types/organization.ts
  src/app/types/user.ts
  src/app/types/zone.ts
  src/app/user/default-organization-form/default-organization-form.component.html
  src/app/user/default-organization-form/default-organization-form.component.scss
  src/app/user/default-organization-form/default-organization-form.component.ts
  src/app/user/user-routing.module.ts
  src/app/user/user-settings/user-settings.component.html
  src/app/user/user-settings/user-settings.component.scss
  src/app/user/user-settings/user-settings.component.ts
  src/app/user/user.module.ts
Labels: enhancement

#155 Update CODEOWNERS
  CODEOWNERS
Labels: documentation

#161 Make zone features configurable.
  deployment/helmfile.yaml
  src/app/app-config.service.ts
  src/app/app.module.ts
  src/app/types/zone.ts
  src/app/zones/zone-features.pipe.ts
  src/app/zones/zones.component.html
  src/app/zones/zones.component.ts
  src/config.json
  src/environments/environment.e2e-development.ts
  src/environments/environment.ts
  src/environments/environment.type.ts
  src/proxy.conf.json
Labels: enhancement
