Repository appuio/cloud-portal, pull requests merged in 2022-09, with the labels that each got.

#318 Unifies menu structure across all documentation sites
  docs/modules/ROOT/nav.adoc
Labels: documentation

#325 🧑‍💻 add angular extended diagnostics
  tsconfig.json
Labels: enhancement

#326 💄 help menu width
  src/app/info-menu-item/info-menu-item.component.html
  src/app/info-menu/info-menu.component.html
  src/app/info-menu/info-menu.component.scss
Labels: enhancement, UX

#327 💄 UI improvements for small screens
  cypress/e2e/organization-members.cy.ts
  cypress/e2e/teams.cy.ts
  src/app/app.component.html
  src/app/app.component.ts
  src/app/first-time-login-dialog/first-time-login-dialog.component.html
  src/app/identity-menu/identity-menu.component.html
  src/app/info-menu-item/info-menu-item.component.html
  src/app/info-menu/info-menu.component.html
  src/app/organization-selection/organization-selection.component.html
  src/app/organizations/organization-members-edit/organization-members-edit.component.html
  src/app/organizations/organization-members-edit/organization-members-edit.component.scss
  src/app/organizations/organizations.component.html
  src/app/teams/teams.component.html
  src/app/zones/zone/zone-detail.component.html
  src/styles.scss
Labels: enhancement

#328 ✨ Embed Productboard
  cypress/e2e/productboard.cy.ts
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.component.ts
  src/app/productboard/productboard-routing.module.ts
  src/app/productboard/productboard.component.html
  src/app/productboard/productboard.component.scss
  src/app/productboard/productboard.component.ts
  src/app/productboard/productboard.module.ts
  src/app/status-badge/status-badge.component.html
Labels: enhancement
