Repository appuio/cloud-portal, pull requests merged in 2022-06, with the labels that each got.

#208 kubeconfig instructions & download
  .gitignore
  cypress/integration/kubeconfig.spec.ts
  deployment/integration.yaml
  deployment/preview.yaml
  src/app/app-config.service.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/info-menu-item/info-menu-item.component.html
  src/app/info-menu-item/info-menu-item.component.scss
  src/app/info-menu-item/info-menu-item.component.ts
  src/app/info-menu/info-menu.component.html
  src/app/info-menu/info-menu.component.ts
  src/app/kubeconfig/kubeconfig-routing.module.ts
  src/app/kubeconfig/kubeconfig.component.html
  src/app/kubeconfig/kubeconfig.component.scss
  src/app/kubeconfig/kubeconfig.component.ts
  src/app/kubeconfig/kubeconfig.module.ts
  src/app/kubeconfig/replace-values.pipe.ts
  src/assets/kubectl-config.template
  src/config.json
  src/environments/environment.e2e-development.ts
  src/environments/environment.ts
Labels: enhancement

#210 Dynamic zone urls and labels
  cypress/fixtures/zone.ts
  cypress/integration/zones.spec.ts
  deployment/helmfile.yaml
  src/app/app-config.service.ts
  src/app/types/zone.ts
  src/app/zones/zone-features.pipe.ts
  src/app/zones/zone-url-label.pipe.ts
  src/app/zones/zone/zone-detail.component.html
  src/app/zones/zones.module.ts
  src/config.json
  src/environments/environment.type.ts
Labels: enhancement

#211 🐛 close menu drawer on small screens
  src/app/app.component.html
  src/app/app.component.scss
  src/app/identity-menu/identity-menu.component.html
  src/app/info-menu/info-menu.component.html
Labels: bug

#212 Retry HTTP requests on network error
  cypress/integration/organizations.spec.ts
  cypress/integration/teams.spec.ts
  cypress/integration/zones.spec.ts
  src/app/app.module.ts
  src/app/core/retry.interceptor.ts
Labels: enhancement

#227 Set nxt-engineering as codeowner.
  CODEOWNERS
Labels: change

#234 Show error message if user details fail to load
  .github/workflows/destroy-preview.yaml
  .github/workflows/template-deploy.yaml
  src/app/store/app.effects.ts
  src/app/user/user-settings/user-settings.component.html
  src/app/user/user-settings/user-settings.component.ts
Labels: bug
