Repository appuio/cloud-portal, pull requests merged in 2022-02, with the labels that each got.

#78 point integration to id dev
  deployment/integration.yaml
Labels: change

#81 Manage organizations
  CODEOWNERS
  angular.json
  cypress/fixtures/organization-update.json
  cypress/fixtures/organizations-empty.json
  cypress/fixtures/organizations.json
  cypress/integration/organizations.spec.ts
  cypress/integration/zones.spec.ts
  cypress/support/commands.ts
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/core/id-token.interceptor.ts
  src/app/core/kubernetes-client.service.ts
  src/app/kubernetes-client.service.ts
  src/app/navbar-item/navbar-item.component.html
  src/app/navbar-item/navbar-item.component.ts
  src/app/organizations/organization-edit/organization-edit.component.html
  src/app/organizations/organization-edit/organization-edit.component.scss
  src/app/organizations/organization-edit/organization-edit.component.ts
  src/app/organizations/organization-form/organization-form.component.html
  src/app/organizations/organization-form/organization-form.component.scss
  src/app/organizations/organization-form/organization-form.component.ts
  src/app/organizations/organizations-routing.module.ts
  src/app/organizations/organizations.component.html
  src/app/organizations/organizations.component.scss
  src/app/organizations/organizations.component.ts
  src/app/organizations/organizations.module.ts
  src/app/organizations/store/organization.actions.ts
  src/app/organizations/store/organization.effects.ts
  src/app/organizations/store/organization.reducer.ts
  src/app/organizations/store/organization.selectors.ts
  src/app/permission.guard.ts
  src/app/shared/shared.module.ts
  src/app/store/app.effects.ts
  src/app/store/app.reducer.ts
  src/app/store/app.selectors.ts
  src/app/store/router.selectors.ts
  src/app/types/entity.ts
  src/app/types/organization.ts
  src/app/types/zone.ts
  src/app/zones/zones.component.ts
  src/styles.scss
Labels: enhancement

#108 Align the row height in the zones table.
  src/app/zones/zones.component.html
  src/app/zones/zones.component.scss
Labels: bug

#107 Add GlitchTip to collect errors.
  .github/workflows/pull-request.yaml
  .github/workflows/template-deploy.yaml
  deployment/helmfile.yaml
  package-lock.json
  package.json
  src/app/app-config.service.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/config.json
Labels: enhancement

#110 Add a section for references.
  src/app/app-routing.module.ts
  src/app/app.component.ts
  src/app/references/references-routing.module.ts
  src/app/references/references.component.html
  src/app/references/references.component.scss
  src/app/references/references.component.ts
  src/app/references/references.module.ts
Labels: enhancement

#109 Add a link to edit the user account.
  src/app/app.component.ts
Labels: enhancement

#111 Add `glitchTipDsn` secret in integration deploy GitHub action
  .github/workflows/master.yaml
Labels: ignore

#86 Edit members of an organization
  .eslintrc.json
  .github/workflows/template-build.yaml
  cypress/fixtures/organization-members.json
  cypress/fixtures/organization-update.json
  cypress/fixtures/organizations.json
  cypress/integration/organization-members.spec.ts
  cypress/integration/organizations.spec.ts
  cypress/support/commands.ts
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/core/kubernetes-client.service.ts
  src/app/organizations/join-organization-dialog/join-organization-dialog.component.html
  src/app/organizations/join-organization-dialog/join-organization-dialog.component.scss
  src/app/organizations/join-organization-dialog/join-organization-dialog.component.ts
  src/app/organizations/organization-edit/organization-edit.component.html
  src/app/organizations/organization-form/organization-form.component.html
  src/app/organizations/organization-form/organization-form.component.ts
  src/app/organizations/organization-members-edit/organization-members-edit.component.html
  src/app/organizations/organization-members-edit/organization-members-edit.component.scss
  src/app/organizations/organization-members-edit/organization-members-edit.component.ts
  src/app/organizations/organization-members-edit/organization-members.resolver.ts
  src/app/organizations/organizations-routing.module.ts
  src/app/organizations/organizations.component.html
  src/app/organizations/organizations.component.ts
  src/app/organizations/organizations.module.ts
  src/app/organizations/store/organization.actions.ts
  src/app/organizations/store/organization.effects.ts
  src/app/organizations/store/organization.reducer.ts
  src/app/shared/shared.module.ts
  src/app/types/organization-members.ts
  src/app/types/organization.ts
  src/app/types/self-subject-access-review.ts
  src/index.html
  src/style/theme.css
  src/styles.scss
Labels: enhancement
