Repository appuio/cloud-portal, pull requests merged in 2023-03, with the labels that each got.

#493 Edit Organizations only with Access to Billing Entities
  cypress/e2e/billingentities.cy.ts
  cypress/e2e/first-time-login.cy.ts
  cypress/e2e/organization-members.cy.ts
  cypress/e2e/organizations.cy.ts
  cypress/fixtures/billingentities.ts
  cypress/fixtures/organization-members.ts
  cypress/fixtures/organization.ts
  src/app/app-routing.module.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/billingentity/billing-entity-routing.module.ts
  src/app/billingentity/billing-entity.component.html
  src/app/billingentity/billing-entity.component.ts
  src/app/billingentity/billing-entity.guard.ts
  src/app/billingentity/billing-entity.module.ts
  src/app/billingentity/billingentity-view/billing-entity-resolver.service.ts
  src/app/billingentity/billingentity-view/billingentity-view.component.html
  src/app/billingentity/billingentity-view/billingentity-view.component.ts
  src/app/core/kubernetes-client.service.ts
  src/app/first-time-login-dialog/first-time-login-dialog.component.ts
  src/app/kubernetes-permission.guard.ts
  src/app/organization-selection/organization-selection.component.html
  src/app/organization-selection/organization-selection.component.ts
  src/app/organizations/organization-collection.service.ts
  src/app/organizations/organization-data.service.ts
  src/app/organizations/organization-edit/organization-edit.component.html
  src/app/organizations/organization-edit/organization-edit.component.ts
  src/app/organizations/organization-edit/organization.resolver.ts
  src/app/organizations/organization-form/organization-form.component.html
  src/app/organizations/organization-form/organization-form.component.ts
  src/app/organizations/organization-members-edit/organization-members-edit.component.html
  src/app/organizations/organization-members-edit/organization-members-edit.component.ts
  src/app/organizations/organization-members-edit/organization-members-edit.resolver.ts
  src/app/organizations/organization-members-edit/organization-members.resolver.ts
  src/app/organizations/organization-members/organization-members-collection.service.ts
  src/app/organizations/organization-members/organization-members-data.service.ts
  src/app/organizations/organization-permission.service.ts
  src/app/organizations/organizations-routing.module.ts
  src/app/organizations/organizations.component.html
  src/app/organizations/organizations.component.ts
  src/app/organizations/organizations.module.ts
  src/app/store/app.effects.ts
  src/app/store/app.reducer.ts
  src/app/store/billingentity-collection.service.ts
  src/app/store/entity-metadata-map.ts
  src/app/store/kubernetes-collection.service.ts
  src/app/store/kubernetes-data.service.ts
  src/app/store/kubernetes-url-generator.service.ts
  src/app/store/organization-collection.service.ts
  src/app/store/organizationmembers-collection.service.ts
  src/app/store/ssar-collection.service.ts
  src/app/store/ssar-data.service.ts
  src/app/teams/teams.component.ts
  src/app/types/billing-entity.ts
  src/app/types/organization-members.ts
  src/app/types/organization.ts
  src/app/types/self-subject-access-review.ts
  src/app/user/default-organization-form/default-organization-form.component.ts
Labels: enhancement

#508 Edit members of Billing Entities
  cypress/e2e/billingentities.cy.ts
  cypress/e2e/billingentity-members.cy.ts
  cypress/fixtures/clusterrole-binding.ts
  cypress/fixtures/clusterrole.ts
  cypress/support/commands.ts
  src/app/billingentity/billing-entity-routing.module.ts
  src/app/billingentity/billing-entity.component.html
  src/app/billingentity/billing-entity.component.ts
  src/app/billingentity/billing-entity.module.ts
  src/app/billingentity/billingentity-members/billingentity-members.component.html
  src/app/billingentity/billingentity-members/billingentity-members.component.scss
  src/app/billingentity/billingentity-members/billingentity-members.component.ts
  src/app/store/app.reducer.ts
  src/app/store/billingentity-collection.service.ts
  src/app/store/cluster-role-collection.service.ts
  src/app/store/clusterrolebinding-collection.service.ts
  src/app/store/entity-metadata-map.ts
  src/app/store/kubernetes-collection.service.ts
  src/app/store/kubernetes-data.service.ts
  src/app/store/ssar-collection.service.ts
  src/app/types/clusterRole.ts
  src/app/types/clusterrole-binding.ts
  src/app/types/entity.ts
  src/app/types/role-binding.ts
  src/app/types/rule.ts
  src/app/types/self-subject-access-review.ts
Labels: enhancement

#510 Navigate back via history
  src/app/app.module.ts
  src/app/billingentity/billingentity-members/billingentity-members.component.html
  src/app/billingentity/billingentity-members/billingentity-members.component.ts
  src/app/billingentity/billingentity-view/billingentity-view.component.html
  src/app/organizations/organization-edit/organization-edit.component.html
  src/app/organizations/organization-form/organization-form.component.ts
  src/app/organizations/organization-members-edit/organization-members-edit.component.html
  src/app/organizations/organization-members-edit/organization-members-edit.component.ts
  src/app/shared/back-link.directive.ts
  src/app/shared/navigation.service.ts
  src/app/shared/shared.module.ts
  src/app/teams/team-edit/team-edit.component.html
  src/app/teams/team-edit/team-edit.component.ts
  src/app/zones/zone/zone-detail.component.html
Labels: enhancement

#509 List invitations
  cypress/e2e/invitations.cy.ts
  cypress/e2e/organization-members.cy.ts
  cypress/e2e/user.cy.ts
  cypress/fixtures/invitations.ts
  src/app/app-routing.module.ts
  src/app/app.component.ts
  src/app/core/retry.interceptor.ts
  src/app/invitations/invitation-detail/invitation-detail.component.html
  src/app/invitations/invitation-detail/invitation-detail.component.scss
  src/app/invitations/invitation-detail/invitation-detail.component.ts
  src/app/invitations/invitation-view/invitation-view.component.html
  src/app/invitations/invitation-view/invitation-view.component.scss
  src/app/invitations/invitation-view/invitation-view.component.ts
  src/app/invitations/invitations-routing.module.ts
  src/app/invitations/invitations.component.html
  src/app/invitations/invitations.component.scss
  src/app/invitations/invitations.component.ts
  src/app/invitations/invitations.module.ts
  src/app/shared/shared.module.ts
  src/app/store/entity-filter.ts
  src/app/store/entity-metadata-map.ts
  src/app/store/invitation-collection.service.ts
  src/app/store/kubernetes-url-generator.service.ts
  src/app/types/invitation.ts
  src/app/types/status.ts
Labels: enhancement

#516 Catch error if user is not found
  cypress/e2e/user.cy.ts
  cypress/fixtures/organization-members.ts
  src/app/app.component.ts
  src/app/identity-menu/identity-menu.component.ts
  src/app/types/user.ts
  src/app/user/default-organization-form/default-organization-form.component.html
  src/app/user/user-edit/user-edit.component.html
  src/app/user/user-edit/user-edit.component.scss
  src/app/user/user-edit/user-edit.component.ts
  src/app/user/user-routing.module.ts
  src/app/user/user-settings/user-settings.component.html
  src/app/user/user-settings/user-settings.component.scss
  src/app/user/user-settings/user-settings.component.ts
  src/app/user/user.module.ts
Labels: bug

#512 Create Invitations
  cypress/e2e/invitations-create.cy.ts
  cypress/e2e/invitations.cy.ts
  cypress/fixtures/invitations.ts
  cypress/fixtures/organization.ts
  cypress/fixtures/team.ts
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/invitations/invitation-edit/invitation-edit.component.html
  src/app/invitations/invitation-edit/invitation-edit.component.scss
  src/app/invitations/invitation-edit/invitation-edit.component.ts
  src/app/invitations/invitation-form/invitation-form.component.html
  src/app/invitations/invitation-form/invitation-form.component.scss
  src/app/invitations/invitation-form/invitation-form.component.ts
  src/app/invitations/invitation-form/invitation-form.types.ts
  src/app/invitations/invitation-form/invitation-form.util.ts
  src/app/invitations/invitations-routing.module.ts
  src/app/invitations/invitations.component.html
  src/app/invitations/invitations.component.ts
  src/app/invitations/invitations.module.ts
  src/app/shared/shared.module.ts
  src/app/store/billingentity-collection.service.ts
  src/app/store/invitation-collection.service.ts
  src/app/store/kubernetes-collection.service.ts
  src/app/store/organization-collection.service.ts
  src/app/teams/team-edit/team-edit.component.ts
  src/app/types/team.ts
Labels: enhancement

#526 Switch CodeOwners to Aldebaran Tech
  CODEOWNERS
Labels: documentation
